

GET http://localhost:3500/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFvdWluYSIsImlhdCI6MTY5ODQ4Nzc1MSwiZXhwIjoxNjk4NDg3ODExfQ.jHMo-wII6pQnhBcUbigraY09c5IidxhP-XQf9fqlnBI